# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: obelab_development
  username: christian
  password: elabs
  host: localhost

#todo
test:
  adapter: mysql
  database: obelab_test
  username: christian
  password: elabs
  host: localhost

production:
  adapter: mysql
  database: methodbox_production
  username: ian
  password:
  socket: /var/mysql/mysql.sock

# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  timeout: 5000

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  timeout: 5000
#
#production:
#  adapter: sqlite3
#  database: db/production.sqlite3
#  timeout: 5000
