#Database configuration for cruise control
development:
  adapter: sqlite3
  database: db/development_cc.sqlite3
  timeout: 5000 

test:
  adapter: sqlite3
  database: db/test_cc.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production_cc.sqlite3
  timeout: 5000
