EMAIL_ENABLED = true
CSV_SERVER_LOCATION='localhost'
CSV_SERVER_PORT='25000'
CSV_SERVER_PATH='/csv-server/eos'
CSV_FILE_PATH='/Users/Ian/csv'
REGISTRATION_CLOSED = true
NEW_CSV_FILE_PATH='/Users/Ian/csv/complete'
