source :gemcutter
gem "rails", "2.3.5"
gem "rmagick", "2.12.2"
gem "RedCloth", "4.2.3"
gem "will_paginate", "2.3.12"
gem "fastercsv", "1.5.3"
gem "libxml-ruby", "1.1.3"
gem "mysql", "2.8.1"
gem "ruby-debug", "0.10.3"
gem "rubyzip", "0.9.1"
gem "sqlite3-ruby", :require => "sqlite3"
gem "uuidtools", "2.1.1"
gem "mime-types", "1.16"
gem "rchardet", "1.3"

# bundler requires these gems in all environments
# gem "nokogiri", "1.4.2"
# gem "geokit"



group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  # bundler requires these gems while running tests
  # gem "rspec"
  # gem "faker"
end
