hse2000:
  id: 1
  title: HSE2000
  surveytype: HSE
  description: Health of Older People & Social Exclusion - includes a sample of care home residents.
  year: 2000
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=4487
  headline_report: http://www.dh.gov.uk/en/Publicationsandstatistics/PublishedSurvey/HealthSurveyForEngland/Healthsurveyresults/DH_4015537
  original_filename: HSE2000.tab

hse2001:
  id: 2
  title: HSE2001
  surveytype: HSE
  description: Respiratory disease and atopic conditions, disability and non-fatal accidents
  year: 2001
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=4628
  headline_report: http://www.archive2.official-documents.co.uk/document/deps/doh/survey01/hse01.htm
  original_filename: HSE2001.tab

hse2002:
  id: 3
  title: HSE2002
  surveytype: HSE
  description: children, young people and maternal health, and included a boost sample of young people aged 0 to 24 years and mothers of infants aged under one year
  year: 2002
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=4912
  headline_report: http://www.dh.gov.uk/en/Publicationsandstatistics/PublishedSurvey/HealthSurveyForEngland/Healthsurveyresults/DH_4001558
  original_filename: HSE2002.tab

hse2003:
  id: 4
  title: HSE2003
  surveytype: HSE
  description: Cardio-vascular disease and risk factors
  year: 2003
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=5098
  headline_report: http://www.dh.gov.uk/en/Publicationsandstatistics/Publications/PublicationsStatistics/DH_4098712
  original_filename: HSE2003.tab

hse2004:
  id: 5
  title: HSE2004
  surveytype: HSE
  description: Health of Ethnic Minorities
  year: 2004
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=5439
  headline_report: http://www.ic.nhs.uk/statistics-and-data-collections/health-and-lifestyles-related-surveys/health-survey-for-england/health-survey-for-england-2004-health-of-ethnic-minorities-headline-tables
  original_filename: HSE2004.tab

hse2005:
  id: 6
  title: HSE2005
  surveytype: HSE
  description: Health of Older People - includes a boost sample of people aged 65 and over resident in private households.
  year: 2005
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=5675
  headline_report: http://www.ic.nhs.uk/statistics-and-data-collections/health-and-lifestyles-related-surveys/health-survey-for-england/health-survey-for-england-2005:-health-of-older-people-%5Bns%5D
  original_filename: HSE2005.tab

hse2006:
  id: 7
  title: HSE2006
  surveytype: HSE
  description: Cardio-vascular disease and risk factors adults, obesity and risk factors children
  year: 2006
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=5809
  headline_report: http://www.ic.nhs.uk/statistics-and-data-collections/health-and-lifestyles-related-surveys/health-survey-for-england/health-survey-for-england-2006:-cvd-and-risk-factors-adults-obesity-and-risk-factors-children
  original_filename: HSE2006.tab

hse2007:
  id: 8
  title: HSE2007
  surveytype: HSE
  description: Healthy lifestyles, knowledge, attitudes and behaviours
  year: 2007
  UKDA_summary: http://www.esds.ac.uk/findingData/snDescription.asp?sn=6112
  headline_report: http://www.ic.nhs.uk/statistics-and-data-collections/health-and-lifestyles-related-surveys/health-survey-for-england/health-survey-for-england-2007:-healthly-lifestyles:-knowledge-attitudes-and-behaviour-%5Bns%5D
  original_filename: HSE2007.tab